In [1]:
import pandas as pd
df_full_data_1 = pd.read_csv(r'suicide2009-2013.txt', sep='\t')
df_full_data_1.head()

,Notes,County,County Code,Year,Year Code,Deaths,Population,Crude Rate,Crude Rate Lower 95% Confidence Interval,Crude Rate Upper 95% Confidence Interval,Age Adjusted Rate,Age Adjusted Rate Lower 95% Confidence Interval,Age Adjusted Rate Upper 95% Confidence Interval
0,NaN,"Autauga County, AL",1001,2009,2009,41,54135,75.7,54.4,102.7,84.3,60.0,115.3
1,NaN,"Autauga County, AL",1001,2010,2010,60,54571,109.9,83.9,141.5,124.0,93.9,160.6
2,NaN,"Autauga County, AL",1001,2011,2011,77,55267,139.3,110.0,174.1,154.3,121.2,193.8
3,NaN,"Autauga County, AL",1001,2012,2012,57,55514,102.7,77.8,133.0,110.5,83.2,143.8
4,NaN,"Autauga County, AL",1001,2013,2013,64,55246,115.8,89.2,147.9,121.2,92.9,155.4

In [2]:
df_full_data_1['Age Adjusted Rate'] = pd.to_numeric(df_full_data_1['Age Adjusted Rate'], errors='coerce')
# no_quotes['Age Adjusted Rate'].max()
# no_quotes['Age Adjusted Rate'].min()
df_full_data_1 = df_full_data_1.sort_values('Age Adjusted Rate',ascending=False)

#This is the way to show deaths occured per year for every 100000 persons
df_full_data_1['Suicide_Death_Rate']=(df_full_data_1['Deaths']/df_full_data_1.Population)*100000
df_full_data_1[:5]

,Notes,County,County Code,Year,Year Code,Deaths,Population,Crude Rate,Crude Rate Lower 95% Confidence Interval,Crude Rate Upper 95% Confidence Interval,Age Adjusted Rate,Age Adjusted Rate Lower 95% Confidence Interval,Age Adjusted Rate Upper 95% Confidence Interval,Suicide_Death_Rate
394,NaN,"Wade Hampton Census Area, AK",2270,2013,2013,31,7977,388.6,264.0,551.6,512.1,320.9,775.3,388.617275
393,NaN,"Wade Hampton Census Area, AK",2270,2012,2012,20,7809,256.1,156.4,395.5,375.4,205.2,629.8,256.114739
10092,NaN,"Todd County, SD",46121,2009,2009,26,9521,273.1,178.4,400.1,355.1,225.1,532.9,273.080559
12665,NaN,"Wyoming County, WV",54109,2011,2011,78,23419,333.1,263.3,415.7,346.7,272.7,434.6,333.062898
374,NaN,"Nome Census Area, AK",2180,2009,2009,25,9313,268.4,173.7,396.3,334.9,201.6,522.9,268.441963

$$ Crude Rate Upper Limit =  (100000/n)*(d+ 1.96 \sqrt{d}) ; d=death; n=population$$

$$ Age Adjusted Rate Upper Limit =  r+(1.96*r/ \sqrt{n}) ; r=age rate; n=death$$

### https://www.health.pa.gov/topics/HealthStatistics/Statistical-Resources/UnderstandingHealthStats/Documents/Confidence_Intervals_for_a_Crude_Rate.pdf
### https://www.health.pa.gov/topics/HealthStatistics/Statistical-Resources/UnderstandingHealthStats/Documents/Confidence_Intervals_for_an_Age_Adjusted_Rate.pdf
### Briefly Calculate Crude/Age-adjusted Rate by provided Confidence intervals

In [3]:
def Deaths_from_population_Upper(n,s):
    return (n*s-196*np.sqrt(10)*np.sqrt(n*s+96040)+192080)/100000
# df_full_data_1['Test']=df_full_data_1.apply(lambda x: Deaths_from_population_Upper(x.Population,x['Crude Rate Upper 95% Confidence Interval']),axis=1)

## Generating 16 intervals of Age adjusted Rate

In [4]:
import numpy as np
def New_Adjusted_Rate(n,s):
    return (25*np.sqrt(n)*s/(25*np.sqrt(n)+49))
df_full_data_1['Calculated_Age_Adjusted_Rate']=df_full_data_1.apply(lambda x: New_Adjusted_Rate(x.Deaths,x['Age Adjusted Rate Upper 95% Confidence Interval']),axis=1)
# df_full_data_1['bin']=pd.cut(df_full_data_1['Calculated_Age_Adjusted_Rate'], bins=16)
# df_full_data_1
df_full_data_1['binned']=pd.cut(df_full_data_1['Calculated_Age_Adjusted_Rate'], bins=10).astype(str)

df_full_data_1

,Notes,County,County Code,Year,Year Code,Deaths,Population,Crude Rate,Crude Rate Lower 95% Confidence Interval,Crude Rate Upper 95% Confidence Interval,Age Adjusted Rate,Age Adjusted Rate Lower 95% Confidence Interval,Age Adjusted Rate Upper 95% Confidence Interval,Suicide_Death_Rate,Calculated_Age_Adjusted_Rate,binned
394,NaN,"Wade Hampton Census Area, AK",2270,2013,2013,31,7977,388.6,264.0,551.6,512.1,320.9,775.3,388.617275,573.435552,"(519.738, 573.436]"
393,NaN,"Wade Hampton Census Area, AK",2270,2012,2012,20,7809,256.1,156.4,395.5,375.4,205.2,629.8,256.114739,437.887390,"(412.344, 466.041]"
10092,NaN,"Todd County, SD",46121,2009,2009,26,9521,273.1,178.4,400.1,355.1,225.1,532.9,273.080559,384.935541,"(358.647, 412.344]"
12665,NaN,"Wyoming County, WV",54109,2011,2011,78,23419,333.1,263.3,415.7,346.7,272.7,434.6,333.062898,355.667932,"(304.95, 358.647]"
374,NaN,"Nome Census Area, AK",2180,2009,2009,25,9313,268.4,173.7,396.3,334.9,201.6,522.9,268.441963,375.646552,"(358.647, 412.344]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13099,NaN,"Washakie County, WY",56043,2013,2013,12,8463,Unreliable,73.3,247.7,NaN,62.5,224.1,141.793690,143.121429,"(90.161, 143.859]"
13100,NaN,"Weston County, WY",56045,2010,2010,14,7208,Unreliable,106.2,325.9,NaN,96.1,308.6,194.228635,202.515758,"(197.556, 251.253]"
13101,NaN,"Weston County, WY",56045,2011,2011,14,7108,Unreliable,107.7,330.5,NaN,99.1,318.3,196.961171,208.881289,"(197.556, 251.253]"
13102,NaN,"Weston County, WY",56045,2012,2012,10,7082,Unreliable,67.7,259.7,NaN,51.0,211.7,141.203050,130.694629,"(90.161, 143.859]"
13103,NaN,"Weston County, WY",56045,2013,2013,13,7158,Unreliable,96.7,310.6,NaN,88.9,300.4,181.614976,194.609222,"(143.859, 197.556]"

## Association with FIPS

In [5]:
import geopandas as gpd
dfg = gpd.read_file('us-counties.json')
# print(type(dfg))

dfg['id'] = dfg['id'].apply(lambda x: x.zfill(5))
df_full_data_1['County Code']=df_full_data_1['County Code'].astype(str)
df_full_data_1['County Code']= df_full_data_1['County Code'].apply(lambda x: x.zfill(5))

df_2013 = df_full_data_1[(df_full_data_1.Year == 2013)]
df_2013.head()

years = sorted(df_full_data_1['Year'].unique().tolist())
years
bins = df_2013['binned'].unique()
bins

array(['(519.738, 573.436]', '(304.95, 358.647]', '(251.253, 304.95]',
       '(197.556, 251.253]', '(143.859, 197.556]', '(90.161, 143.859]',
       '(35.927, 90.161]', '(412.344, 466.041]'], dtype=object)

In [6]:
df_2013

,Notes,County,County Code,Year,Year Code,Deaths,Population,Crude Rate,Crude Rate Lower 95% Confidence Interval,Crude Rate Upper 95% Confidence Interval,Age Adjusted Rate,Age Adjusted Rate Lower 95% Confidence Interval,Age Adjusted Rate Upper 95% Confidence Interval,Suicide_Death_Rate,Calculated_Age_Adjusted_Rate,binned
394,NaN,"Wade Hampton Census Area, AK",02270,2013,2013,31,7977,388.6,264.0,551.6,512.1,320.9,775.3,388.617275,573.435552,"(519.738, 573.436]"
10096,NaN,"Todd County, SD",46121,2013,2013,25,9982,250.5,162.1,369.7,317.8,199.2,481.1,250.450811,345.617816,"(304.95, 358.647]"
9057,NaN,"Jefferson County, OK",40067,2013,2013,23,6432,357.6,226.7,536.6,306.5,189.7,468.5,357.587065,332.578908,"(304.95, 358.647]"
12530,NaN,"McDowell County, WV",54047,2013,2013,63,20876,301.8,231.9,386.1,286.0,217.2,369.7,301.781951,296.486561,"(251.253, 304.95]"
11478,NaN,"Carbon County, UT",49007,2013,2013,56,20988,266.8,201.6,346.5,270.9,202.3,355.2,266.819135,281.476735,"(251.253, 304.95]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13038,NaN,"Crook County, WY",56011,2013,2013,12,7184,Unreliable,86.3,291.8,NaN,73.0,261.8,167.037862,167.198527,"(143.859, 197.556]"
13048,NaN,"Goshen County, WY",56015,2013,2013,14,13612,Unreliable,56.2,172.6,NaN,47.9,162.0,102.850426,106.310930,"(90.161, 143.859]"
13075,NaN,"Platte County, WY",56031,2013,2013,13,8765,Unreliable,79.0,253.6,NaN,55.7,199.8,148.317171,129.437159,"(90.161, 143.859]"
13099,NaN,"Washakie County, WY",56043,2013,2013,12,8463,Unreliable,73.3,247.7,NaN,62.5,224.1,141.793690,143.121429,"(90.161, 143.859]"
13103,NaN,"Weston County, WY",56045,2013,2013,13,7158,Unreliable,96.7,310.6,NaN,88.9,300.4,181.614976,194.609222,"(143.859, 197.556]"

In [7]:
for yr in years:
    df_single_year = df_full_data_1[(df_full_data_1.Year == yr)]
    merged = dfg.merge(df_single_year, right_on='County Code', left_on='id' )
    for bin in bins:
        print(yr,bin)
        geo_layer = merged[(merged['binned'] == bin)] # geo
        try:
            geo_layer.to_file("{0}/{1}.geojson".format(yr, bin), driver='GeoJSON')
        except:
            print('err')
merged = dfg.merge(df_2013, right_on='County Code', left_on='id' )
merged = merged.drop(columns=['Notes','Year Code'])
merged.head()
merged.to_csv('age_adjusted_death_rate_suicide.csv')

2009 (519.738, 573.436]
err
2009 (304.95, 358.647]
2009 (251.253, 304.95]
err
2009 (197.556, 251.253]
err
2009 (143.859, 197.556]
err
2009 (90.161, 143.859]

/anaconda3/envs/newEnv/lib/python3.7/site-packages/geopandas/io/file.py:62: FionaDeprecationWarning: Use fiona.Env() instead.
  with fiona.drivers():

err
2009 (35.927, 90.161]
err
2009 (412.344, 466.041]
2010 (519.738, 573.436]
err
2010 (304.95, 358.647]
err
2010 (251.253, 304.95]
err
2010 (197.556, 251.253]
err
2010 (143.859, 197.556]
err
2010 (90.161, 143.859]
err
2010 (35.927, 90.161]
err
2010 (412.344, 466.041]
err
2011 (519.738, 573.436]
err
2011 (304.95, 358.647]
err
2011 (251.253, 304.95]
2011 (197.556, 251.253]
err
2011 (143.859, 197.556]
err
2011 (90.161, 143.859]
err
2011 (35.927, 90.161]
err
2011 (412.344, 466.041]
err
2012 (519.738, 573.436]
err
2012 (304.95, 358.647]
2012 (251.253, 304.95]
err
2012 (197.556, 251.253]
2012 (143.859, 197.556]
err
2012 (90.161, 143.859]
err
2012 (35.927, 90.161]
err
2012 (412.344, 466.041]
2013 (519.738, 573.436]
2013 (304.95, 358.647]
2013 (251.253, 304.95]
err
2013 (197.556, 251.253]
2013 (143.859, 197.556]
err
2013 (90.161, 143.859]
err
2013 (35.927, 90.161]
err
2013 (412.344, 466.041]

In [8]:
# for bin in bins:
#     geo_layer = merged[(merged['binned'] == bin)] # geo
#     print(geo_layer)
#     geo_layer.to_file("{0}.geojson".format(bin), driver='GeoJSON')